In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
data = pd.read_csv(r'E:\xeeva task\Data Scientist - Assignment\Assignment-2\Data\TestParam.csv')
data.head()

label  param0  param1  param2  param3  param4  param5  param6  param7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   param8  ...  param774  param775  param776  param777  param778  param779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   param780  param781  param782  param783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [4]:
data.describe()

label   param0   param1   param2   param3   param4   param5  \
count  42000.000000  42000.0  42000.0  42000.0  42000.0  42000.0  42000.0   
mean       4.456643      0.0      0.0      0.0      0.0      0.0      0.0   
std        2.887730      0.0      0.0      0.0      0.0      0.0      0.0   
min        0.000000      0.0      0.0      0.0      0.0      0.0      0.0   
25%        2.000000      0.0      0.0      0.0      0.0      0.0      0.0   
50%        4.000000      0.0      0.0      0.0      0.0      0.0      0.0   
75%        7.000000      0.0      0.0      0.0      0.0      0.0      0.0   
max        9.000000      0.0      0.0      0.0      0.0      0.0      0.0   

        param6   param7   param8  ...      param774      param775  \
count  42000.0  42000.0  42000.0  ...  42000.000000  42000.000000   
mean       0.0      0.0      0.0  ...      0.219286      0.117095   
std        0.0      0.0      0.0  ...      6.312890      4.633819   
min        0.0      0.0      0.0  ...      0.000000      0.000000   
25%        0.0      0.0      0.0  ...      0.000000      0.000000   
50%        0.0      0.0      0.0  ...      0.000000      0.000000   
75%        0.0      0.0      0.0  ...      0.000000      0.000000   
max        0.0      0.0      0.0  ...    254.000000    254.000000   

           param776     param777      param778      param779  param780  \
count  42000.000000  42000.00000  42000.000000  42000.000000   42000.0   
mean       0.059024      0.02019      0.017238      0.002857       0.0   
std        3.274488      1.75987      1.894498      0.414264       0.0   
min        0.000000      0.00000      0.000000      0.000000       0.0   
25%        0.000000      0.00000      0.000000      0.000000       0.0   
50%        0.000000      0.00000      0.000000      0.000000       0.0   
75%        0.000000      0.00000      0.000000      0.000000       0.0   
max      253.000000    253.00000    254.000000     62.000000       0.0   

       param781  param782  param783  
count   42000.0   42000.0   42000.0  
mean        0.0       0.0       0.0  
std         0.0       0.0       0.0  
min         0.0       0.0       0.0  
25%         0.0       0.0       0.0  
50%         0.0       0.0       0.0  
75%         0.0       0.0       0.0  
max         0.0       0.0       0.0  

[8 rows x 785 columns]

In [5]:
# drop columns with only null values
data=data.loc[:, (data != 0).any(axis=0)]

In [6]:
data.describe()

label      param12       param13       param14       param15  \
count  42000.000000  42000.00000  42000.000000  42000.000000  42000.000000   
mean       4.456643      0.00300      0.011190      0.005143      0.000214   
std        2.887730      0.56812      1.626927      1.053972      0.043916   
min        0.000000      0.00000      0.000000      0.000000      0.000000   
25%        2.000000      0.00000      0.000000      0.000000      0.000000   
50%        4.000000      0.00000      0.000000      0.000000      0.000000   
75%        7.000000      0.00000      0.000000      0.000000      0.000000   
max        9.000000    116.00000    254.000000    216.000000      9.000000   

            param32       param33       param34       param35       param36  \
count  42000.000000  42000.000000  42000.000000  42000.000000  42000.000000   
mean       0.000381      0.001310      0.010548      0.027262      0.050905   
std        0.078072      0.232634      1.131661      2.310396      3.121847   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      0.000000      0.000000      0.000000   
50%        0.000000      0.000000      0.000000      0.000000      0.000000   
75%        0.000000      0.000000      0.000000      0.000000      0.000000   
max       16.000000     47.000000    157.000000    254.000000    255.000000   

       ...      param770     param771      param772      param773  \
count  ...  42000.000000  42000.00000  42000.000000  42000.000000   
mean   ...      0.677857      0.60281      0.489238      0.340214   
std    ...     11.254931     10.69603      9.480066      7.950251   
min    ...      0.000000      0.00000      0.000000      0.000000   
25%    ...      0.000000      0.00000      0.000000      0.000000   
50%    ...      0.000000      0.00000      0.000000      0.000000   
75%    ...      0.000000      0.00000      0.000000      0.000000   
max    ...    255.000000    255.00000    255.000000    255.000000   

           param774      param775      param776     param777      param778  \
count  42000.000000  42000.000000  42000.000000  42000.00000  42000.000000   
mean       0.219286      0.117095      0.059024      0.02019      0.017238   
std        6.312890      4.633819      3.274488      1.75987      1.894498   
min        0.000000      0.000000      0.000000      0.00000      0.000000   
25%        0.000000      0.000000      0.000000      0.00000      0.000000   
50%        0.000000      0.000000      0.000000      0.00000      0.000000   
75%        0.000000      0.000000      0.000000      0.00000      0.000000   
max      254.000000    254.000000    253.000000    253.00000    254.000000   

           param779  
count  42000.000000  
mean       0.002857  
std        0.414264  
min        0.000000  
25%        0.000000  
50%        0.000000  
75%        0.000000  
max       62.000000  

[8 rows x 709 columns]

In [7]:
data.shape

(42000, 709)

In [8]:
X = data.iloc[:,1:]
y = data.iloc[:,0]

In [9]:
# split into train test and validation

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.25, random_state=1) # 0.25 x 0.8 = 0.2

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score

In [23]:
# Using the validation data first:-

# Create the classifier: logreg
logreg = LogisticRegression(random_state=31)
# Fit the classifier to the training data
logreg.fit(X_train,y_train)
# Predict the labels of the val set: y_pred
y_pred = logreg.predict(X_val)
# Compute and print the confusion matrix and classification report
print(confusion_matrix(y_val, y_pred))
print(classification_report(y_val, y_pred))


[[816   0   4   4   1   8   7   6   3   3]
 [  0 878   4   4   1   2   2   2   8   2]
 [  7   6 732  10  12   5  15   9  18   6]
 [  2   6  32 713   0  30   2   8  19  10]
 [  4   5   9   0 735   1   6   5   8  24]
 [  8   6   7  33  12 680  19   3  29  10]
 [ 11   2   9   0  11  13 784   1   3   0]
 [  1   3  11   6   8   1   2 829   8  32]
 [  8  17  12  27   5  27  10   2 701  16]
 [  1   7   2  12  22   7   0  24   8 756]]
              precision    recall  f1-score   support

           0       0.95      0.96      0.95       852
           1       0.94      0.97      0.96       903
           2       0.89      0.89      0.89       820
           3       0.88      0.87      0.87       822
           4       0.91      0.92      0.92       797
           5       0.88      0.84      0.86       807
           6       0.93      0.94      0.93       834
           7       0.93      0.92      0.93       901
           8       0.87      0.85      0.86       825
           9       0.88     

In [24]:
# accuracy score using validation data:-

print('accuracy_score: '+str(accuracy_score(y_val,y_pred)))

accuracy_score: 0.9076190476190477


In [13]:
# Now using the test data :-

# Create the classifier: logreg
logreg = LogisticRegression(random_state=32)
# Fit the classifier to the training data
logreg.fit(X_train,y_train)
# Predict the labels of the test set: y_pred
y_pred = logreg.predict(X_test)
# Compute and print the confusion matrix and classification report
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[822   0   5   1   3   6  11   2   2   1]
 [  0 916   7   4   0   2   2   0   8   1]
 [  4   8 766  10   4   9   6  10  15   3]
 [  1   2  27 763   0  35   1  10  24  10]
 [  1   1   5   1 774   1   5   4   6  31]
 [  8   5   8  31   9 613  14   3  34   6]
 [  3   0   4   0   6  11 769   1   4   2]
 [  0   0   9   5   4   0   1 788   2  41]
 [  5  18  14  26   2  29   6   2 729  15]
 [  3   5   0   5  28   5   0  34  10 753]]
              precision    recall  f1-score   support

           0       0.97      0.96      0.97       853
           1       0.96      0.97      0.97       940
           2       0.91      0.92      0.91       835
           3       0.90      0.87      0.89       873
           4       0.93      0.93      0.93       829
           5       0.86      0.84      0.85       731
           6       0.94      0.96      0.95       800
           7       0.92      0.93      0.92       850
           8       0.87      0.86      0.87       846
           9       0.87     

In [21]:
# accuracy score using test data:-

print('accuracy_score: '+str(accuracy_score(y_test,y_pred)))

accuracy_score: 0.9158333333333334
